spring.application.name=spring_boot_api

spring.datasource.url=jdbc:postgresql://localhost:5432/campus_food_delivery
spring.datasource.username=postgres
spring.datasource.password=KaitoUser_9148
#spring.datasource.password=1234

server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
